import type { Category } from "@/types/tools";

export const allCategories: Category[] = [
  {
    id: "pdf",
    name: "PDF Tools",
    emoji: "📄",
    href: "/tools/pdf",
    gradient: "from-red-500/20 to-orange-500/20",
    border: "border-red-500/20",
    tools: [
      { name: "Compress PDF", href: "/tools/compress-pdf", desc: "Reduce PDF file size instantly" },
      { name: "Merge PDF", href: "/tools/merge-pdf", desc: "Combine multiple PDFs into one" },
      { name: "Split PDF", href: "/tools/split-pdf", desc: "Split PDF into separate pages" },
      { name: "Rotate PDF", href: "/tools/rotate-pdf", desc: "Rotate PDF pages to any angle" },
      { name: "Unlock PDF", href: "/tools/unlock-pdf", desc: "Remove PDF password protection" },
      { name: "Protect PDF", href: "/tools/protect-pdf", desc: "Add password to PDF file" },
      { name: "OCR PDF", href: "/tools/ocr", desc: "Extract text from scanned PDF" },
      { name: "Sign PDF", href: "/tools/sign-pdf", desc: "Add digital signature to PDF" },
      { name: "Watermark PDF", href: "/tools/watermark-pdf", desc: "Add watermark to PDF pages" },
      { name: "PDF to Word", href: "/tools/pdf-to-word", desc: "Convert PDF to editable Word doc" },
      { name: "PDF to Excel", href: "/tools/pdf-to-excel", desc: "Extract tables from PDF to Excel/CSV" },
      { name: "PDF to Text", href: "/tools/pdf-to-text", desc: "Extract all text from any PDF file" },
      { name: "PDF to JPG", href: "/tools/pdf-to-jpg", desc: "Convert PDF pages to images" },
      { name: "JPG to PDF", href: "/tools/jpg-to-pdf", desc: "Convert images to PDF" },
      { name: "Word to PDF", href: "/tools/word-to-pdf", desc: "Convert Word documents to PDF" },
      { name: "AI PDF Summarizer", href: "/tools/ai-pdf-summarizer", desc: "Summarize PDF with AI", badge: "AI" },
    ],
  },
  {
    id: "image",
    name: "Image Tools",
    emoji: "🖼️",
    href: "/tools/image",
    gradient: "from-blue-500/20 to-cyan-500/20",
    border: "border-blue-500/20",
    tools: [
      { name: "Remove Background", href: "/tools/remove-background", desc: "AI background removal", badge: "AI" },
      { name: "Signature to PNG", href: "/tools/signature-png", desc: "Extract signature as transparent PNG", badge: "AI" },
      { name: "Upscale Image", href: "/tools/upscale-image", desc: "Enhance resolution with AI", badge: "AI" },
      { name: "Resize Image", href: "/tools/resize-image", desc: "Resize to any dimension" },
      { name: "Compress Image", href: "/tools/compress-image", desc: "Reduce image file size" },
      { name: "Convert Image", href: "/tools/convert-image", desc: "Convert between image formats" },
      { name: "Blur Background", href: "/tools/blur-background", desc: "Blur image background with AI", badge: "AI" },
      { name: "QR Code Generator", href: "/tools/qr-code-generator", desc: "Create custom QR codes" },
      { name: "Meme Generator", href: "/tools/meme-generator", desc: "Create memes with custom text" },
      { name: "Image Cropper", href: "/tools/image-cropper", desc: "Crop images to any size" },
      { name: "Color Picker", href: "/tools/color-picker", desc: "Pick colors from any image" },
      { name: "Screenshot Editor", href: "/tools/screenshot-editor", desc: "Edit and annotate screenshots" },
    ],
  },
  {
    id: "ai",
    name: "AI Tools",
    emoji: "🤖",
    href: "/tools/ai",
    gradient: "from-purple-500/20 to-pink-500/20",
    border: "border-purple-500/20",
    tools: [
      { name: "AI Writer", href: "/tools/ai-writer", desc: "Generate content with AI", badge: "AI" },
      { name: "AI Summarizer", href: "/tools/ai-summarizer", desc: "Summarize any text instantly", badge: "AI" },
      { name: "AI Paraphraser", href: "/tools/ai-paraphraser", desc: "Rewrite text in new words", badge: "AI" },
      { name: "AI Translator", href: "/tools/ai-translator", desc: "Translate text to any language", badge: "AI" },
      { name: "AI Blog Generator", href: "/tools/ai-blog-generator", desc: "Generate full blog posts", badge: "AI" },
      { name: "AI Email Writer", href: "/tools/ai-email-writer", desc: "Write professional emails", badge: "AI" },
      { name: "AI Headline Generator", href: "/tools/ai-headline-generator", desc: "Create compelling headlines", badge: "AI" },
      { name: "AI Hashtag Generator", href: "/tools/ai-hashtag-generator", desc: "Generate trending hashtags", badge: "AI" },
      { name: "AI Resume Builder", href: "/tools/ai-resume-builder", desc: "Build professional resume with AI", badge: "AI" },
      { name: "AI Chat Workspace", href: "/tools/ai-chat", desc: "Chat with AI assistant", badge: "AI" },
      { name: "Speech to Text", href: "/tools/speech-to-text", desc: "Transcribe audio with AI", badge: "AI" },
    ],
  },
  {
    id: "video",
    name: "Video Tools",
    emoji: "🎬",
    href: "/tools/video",
    gradient: "from-green-500/20 to-teal-500/20",
    border: "border-green-500/20",
    tools: [
      { name: "Trim Video", href: "/tools/trim-video", desc: "Cut and trim video clips" },
      { name: "Compress Video", href: "/tools/compress-video", desc: "Reduce video file size" },
      { name: "Video to MP3", href: "/tools/video-to-mp3", desc: "Extract audio from video" },
      { name: "Add Subtitle", href: "/tools/add-subtitle", desc: "Add subtitles to video" },
      { name: "Extract Audio", href: "/tools/extract-audio", desc: "Extract audio track from video" },
      { name: "Merge Videos", href: "/tools/merge-videos", desc: "Combine multiple videos" },
      { name: "GIF Maker", href: "/tools/gif-maker", desc: "Convert video to GIF" },
    ],
  },
  {
    id: "audio",
    name: "Audio Tools",
    emoji: "🎵",
    href: "/tools/audio",
    gradient: "from-yellow-500/20 to-orange-500/20",
    border: "border-yellow-500/20",
    tools: [
      { name: "Audio Converter", href: "/tools/audio-converter", desc: "Convert audio formats" },
      { name: "MP3 Cutter", href: "/tools/mp3-cutter", desc: "Cut and trim MP3 files" },
      { name: "Text to Speech", href: "/tools/text-to-speech", desc: "Convert text to audio", badge: "AI" },
      { name: "Noise Remover", href: "/tools/noise-remover", desc: "Remove background noise", badge: "AI" },
      { name: "Voice Recorder", href: "/tools/voice-recorder", desc: "Record audio in browser" },

    ],
  },
  {
    id: "developer",
    name: "Developer Tools",
    emoji: "💻",
    href: "/tools/developer",
    gradient: "from-indigo-500/20 to-violet-500/20",
    border: "border-indigo-500/20",
    tools: [
      { name: "JSON Formatter", href: "/tools/json-formatter", desc: "Format and validate JSON" },
      { name: "JWT Decoder", href: "/tools/jwt-decoder", desc: "Decode JWT tokens instantly" },
      { name: "UUID Generator", href: "/tools/uuid-generator", desc: "Generate unique UUIDs" },
      { name: "Regex Tester", href: "/tools/regex-tester", desc: "Test regular expressions" },
      { name: "Base64 Encoder", href: "/tools/base64", desc: "Encode and decode Base64" },
      { name: "Diff Checker", href: "/tools/diff-checker", desc: "Compare two code snippets" },
      { name: "Markdown Previewer", href: "/tools/markdown-previewer", desc: "Preview Markdown live" },
      { name: "Password Generator", href: "/tools/password-generator", desc: "Generate secure passwords" },
      { name: "MD5 Generator", href: "/tools/md5-generator", desc: "Generate MD5 hash" },
    ],
  },
  {
    id: "seo",
    name: "SEO Tools",
    emoji: "📈",
    href: "/tools/seo",
    gradient: "from-emerald-500/20 to-green-500/20",
    border: "border-emerald-500/20",
    tools: [
      { name: "Meta Tag Generator", href: "/tools/meta-tag-generator", desc: "Generate HTML meta tags" },
      { name: "Robots.txt Generator", href: "/tools/robots-txt-generator", desc: "Create robots.txt file" },
      { name: "Sitemap Generator", href: "/tools/sitemap-generator", desc: "Generate XML sitemap" },
      { name: "Keyword Density Checker", href: "/tools/keyword-density", desc: "Analyze keyword usage" },
      { name: "SERP Preview", href: "/tools/serp-preview", desc: "Preview Google search snippet" },
    ],
  },
  {
    id: "text",
    name: "Text Tools",
    emoji: "✍️",
    href: "/tools/text",
    gradient: "from-pink-500/20 to-rose-500/20",
    border: "border-pink-500/20",
    tools: [
      { name: "Word Counter", href: "/tools/word-counter", desc: "Count words and characters" },
      { name: "Grammar Checker", href: "/tools/grammar-checker", desc: "Check and fix grammar", badge: "AI" },
      { name: "Lorem Ipsum Generator", href: "/tools/lorem-ipsum", desc: "Generate placeholder text" },
      { name: "Text Compare", href: "/tools/text-compare", desc: "Compare two texts side-by-side" },
      { name: "Case Converter", href: "/tools/case-converter", desc: "Convert text case instantly" },
      { name: "Fancy Font Generator", href: "/tools/fancy-font", desc: "Generate stylish text fonts" },
    ],
  },
  {
    id: "security",
    name: "Security Tools",
    emoji: "🔒",
    href: "/tools/security",
    gradient: "from-red-500/20 to-pink-500/20",
    border: "border-red-500/20",
    tools: [
    ],
  },
  {
    id: "calculators",
    name: "Calculators",
    emoji: "🧮",
    href: "/tools/calculators",
    gradient: "from-cyan-500/20 to-blue-500/20",
    border: "border-cyan-500/20",
    tools: [
      { name: "BMI Calculator", href: "/tools/bmi-calculator", desc: "Calculate body mass index" },
      { name: "Age Calculator", href: "/tools/age-calculator", desc: "Calculate exact age from birthdate" },
      { name: "Percentage Calculator", href: "/tools/percentage-calculator", desc: "Calculate percentages instantly" },
      { name: "Loan Calculator", href: "/tools/loan-calculator", desc: "Calculate loan payments" },
      { name: "Currency Converter", href: "/tools/currency-converter", desc: "Convert between currencies" },
      { name: "Scientific Calculator", href: "/tools/scientific-calculator", desc: "Advanced math calculator" },
    ],
  },
  {
    id: "productivity",
    name: "Productivity Tools",
    emoji: "⚡",
    href: "/tools/productivity",
    gradient: "from-amber-500/20 to-yellow-500/20",
    border: "border-amber-500/20",
    tools: [
      { name: "Pomodoro Timer", href: "/tools/pomodoro-timer", desc: "Focus timer for productivity" },
      { name: "To-Do List", href: "/tools/todo-list", desc: "Simple task manager" },
      { name: "Habit Tracker", href: "/tools/habit-tracker", desc: "Track daily habits" },
      { name: "AI Meeting Notes", href: "/tools/ai-meeting-notes", desc: "Summarize meetings with AI", badge: "AI" },
    ],
  },
  {
    id: "social-media",
    name: "Social Media Tools",
    emoji: "📱",
    href: "/tools/social-media",
    gradient: "from-fuchsia-500/20 to-purple-500/20",
    border: "border-fuchsia-500/20",
    tools: [
      { name: "AI Caption Generator", href: "/tools/ai-caption-generator", desc: "Generate social media captions", badge: "AI" },
      { name: "AI Tweet Generator", href: "/tools/ai-tweet-generator", desc: "Write viral tweets with AI", badge: "AI" },
      { name: "YouTube Title Generator", href: "/tools/youtube-title-generator", desc: "Generate YouTube titles", badge: "AI" },
      { name: "Thumbnail Generator", href: "/tools/thumbnail-generator", desc: "Create YouTube thumbnails" },
    ],
  },
  {
    id: "student",
    name: "Student Tools",
    emoji: "🎓",
    href: "/tools/student",
    gradient: "from-teal-500/20 to-cyan-500/20",
    border: "border-teal-500/20",
    tools: [
      { name: "AI Homework Helper", href: "/tools/homework-helper", desc: "Get help with homework using AI", badge: "AI" },
      { name: "Citation Generator", href: "/tools/citation-generator", desc: "Generate citations and references" },
      { name: "Essay Writer", href: "/tools/essay-writer", desc: "Write essays with AI help", badge: "AI" },
      { name: "GPA Calculator", href: "/tools/gpa-calculator", desc: "Calculate your GPA" },
      { name: "Math Solver", href: "/tools/math-solver", desc: "Solve math problems with AI", badge: "AI" },
    ],
  },
  {
    id: "business",
    name: "Business Tools",
    emoji: "💼",
    href: "/tools/business",
    gradient: "from-slate-500/20 to-gray-500/20",
    border: "border-slate-500/20",
    tools: [
      { name: "Invoice Generator", href: "/tools/invoice-generator", desc: "Create professional invoices" },
      { name: "Resume Builder", href: "/tools/resume-builder", desc: "Build a professional resume" },
      { name: "Business Name Generator", href: "/tools/business-name-generator", desc: "Generate creative business names", badge: "AI" },
    ],
  },
  {
    id: "browser",
    name: "Browser Utilities",
    emoji: "🌐",
    href: "/tools/browser",
    gradient: "from-sky-500/20 to-blue-500/20",
    border: "border-sky-500/20",
    tools: [
      { name: "Screen Recorder", href: "/tools/screen-recorder", desc: "Record your screen in browser" },
      { name: "Webcam Recorder", href: "/tools/webcam-recorder", desc: "Record webcam video" },
      { name: "Internet Speed Test", href: "/tools/internet-speed-test", desc: "Test your internet speed" },
      { name: "QR Scanner", href: "/tools/qr-scanner", desc: "Scan QR codes with camera" },
    ],
  },
];

export const getTotalToolCount = () =>
  allCategories.reduce((sum, cat) => sum + cat.tools.length, 0);

export const getCategoryById = (id: string) =>
  allCategories.find((c) => c.id === id);

export const getAllTools = () => allCategories.flatMap((c) => c.tools);

export const getAllToolsWithCategory = () =>
  allCategories.flatMap((c) =>
    c.tools.map((t) => ({ ...t, category: c.id }))
  );
